name: Test

on:
  pull_request:
    branches: []
  
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: swift test

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test macOS
        run: swift test

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: MaxDesiatov/swift-windows-action@v1
        with:
          swift-version: "5.6"
          shell-action: swift test
      